
<HTML>
<HEAD>

<TITLE>Some Title</TITLE>
</HEAD>

<FRAMESET cols="20%,80%*,0%" frameborder="0" BORDER="0" NORESIZE>

<FRAME SRC="" NAME="body" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" NORESIZE>

<FRAME SRC="/shopping/servlet/classic39" NAME="body" SCROLLING="yes" MARGINHEIGHT="0" MARGINWIDTH="0" NORESIZE>

<FRAME SRC="" NAME="body" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" NORESIZE>

</FRAMESET>

<NOFRAMES>


</NOFRAMES>

</FRAMESET>
</HTML> 